// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_api_keys_decrypt from "./routes/api/api-keys/decrypt.ts";
import * as $api_api_keys_encrypt from "./routes/api/api-keys/encrypt.ts";
import * as $audio_create_speech from "./routes/audio/create-speech.tsx";
import * as $audio_create_transcription from "./routes/audio/create-transcription.tsx";
import * as $audio_create_translation from "./routes/audio/create-translation.tsx";
import * as $chat_create_chat_completion from "./routes/chat/create-chat-completion.tsx";
import * as $images_create_image_edit from "./routes/images/create-image-edit.tsx";
import * as $images_create_image_variation from "./routes/images/create-image-variation.tsx";
import * as $images_create_image from "./routes/images/create-image.tsx";
import * as $index from "./routes/index.tsx";
import * as $moderations_create_moderation from "./routes/moderations/create-moderation.tsx";
import * as $Alert from "./islands/Alert.tsx";
import * as $ApiKeyConfigure from "./islands/ApiKeyConfigure.tsx";
import * as $ButtonDonate from "./islands/ButtonDonate.tsx";
import * as $ButtonMenu from "./islands/ButtonMenu.tsx";
import * as $FormCreateChatCompletion from "./islands/FormCreateChatCompletion.tsx";
import * as $FormCreateImage from "./islands/FormCreateImage.tsx";
import * as $FormCreateImageEdit from "./islands/FormCreateImageEdit.tsx";
import * as $FormCreateImageVariation from "./islands/FormCreateImageVariation.tsx";
import * as $FormCreateModeration from "./islands/FormCreateModeration.tsx";
import * as $FormCreateSpeech from "./islands/FormCreateSpeech.tsx";
import * as $FormCreateTranscription from "./islands/FormCreateTranscription.tsx";
import * as $FormCreateTranslation from "./islands/FormCreateTranslation.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/api-keys/decrypt.ts": $api_api_keys_decrypt,
    "./routes/api/api-keys/encrypt.ts": $api_api_keys_encrypt,
    "./routes/audio/create-speech.tsx": $audio_create_speech,
    "./routes/audio/create-transcription.tsx": $audio_create_transcription,
    "./routes/audio/create-translation.tsx": $audio_create_translation,
    "./routes/chat/create-chat-completion.tsx": $chat_create_chat_completion,
    "./routes/images/create-image-edit.tsx": $images_create_image_edit,
    "./routes/images/create-image-variation.tsx":
      $images_create_image_variation,
    "./routes/images/create-image.tsx": $images_create_image,
    "./routes/index.tsx": $index,
    "./routes/moderations/create-moderation.tsx":
      $moderations_create_moderation,
  },
  islands: {
    "./islands/Alert.tsx": $Alert,
    "./islands/ApiKeyConfigure.tsx": $ApiKeyConfigure,
    "./islands/ButtonDonate.tsx": $ButtonDonate,
    "./islands/ButtonMenu.tsx": $ButtonMenu,
    "./islands/FormCreateChatCompletion.tsx": $FormCreateChatCompletion,
    "./islands/FormCreateImage.tsx": $FormCreateImage,
    "./islands/FormCreateImageEdit.tsx": $FormCreateImageEdit,
    "./islands/FormCreateImageVariation.tsx": $FormCreateImageVariation,
    "./islands/FormCreateModeration.tsx": $FormCreateModeration,
    "./islands/FormCreateSpeech.tsx": $FormCreateSpeech,
    "./islands/FormCreateTranscription.tsx": $FormCreateTranscription,
    "./islands/FormCreateTranslation.tsx": $FormCreateTranslation,
    "./islands/Sidebar.tsx": $Sidebar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
