// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $audio_create_speech from "./routes/audio/create-speech.tsx";
import * as $index from "./routes/index.tsx";
import * as $ApiKeyManage from "./islands/ApiKeyManage.tsx";
import * as $ButtonDonate from "./islands/ButtonDonate.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/joke.ts": $api_joke,
    "./routes/audio/create-speech.tsx": $audio_create_speech,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ApiKeyManage.tsx": $ApiKeyManage,
    "./islands/ButtonDonate.tsx": $ButtonDonate,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
